Bump dependencies
BP-WG/bp-foundation pull request #18
Opened 2023-04-11 22:56 UTC by crisdut

Hi @dr-orlovsky,

This PR bump the  rust-amplify dependency to version 4.x.

2023-04-15 09:30 UTC, dr-orlovsky requested changes
Cool, but I think we must avoid using all these `.0` and `.as_inners()` since they will be very polluting the code downstream. Instead we need to add `#[wrapper(Deref)]` to all types deriving `Wrapper` in this library (that's the change in amplify 4.0: wrapper doesn't adds Deref impl by default and requires explicit flag for that).

2023-04-25 11:01 UTC, cryptoquick requested changes
I've been doing some research into how to resolve [CVE-2020-26235](https://nvd.nist.gov/vuln/detail/CVE-2020-26235), the infamous time/chrono CVE, and it looks like this crate is one of the core places where this is depended on in the RGB ecosystem according to `cargo tree -i time@0.1.45` in `bitmask-core 0.6.0-beta.0`.

2023-04-25 11:01 UTC, cryptoquick commented on bitcoin_scripts/Cargo.toml
>  secp256k1 = { version = "0.24.2", features = ["global-context"] } # Remove after bitcoin #922
It looks like all of these PRs have been merged:
https://github.com/rust-bitcoin/rust-bitcoin/pull/922#issuecomment-1084585501
I think this comment can be addressed, @dr-orlovsky? Can you provide more background on what this note means?

2023-04-25 11:01 UTC, cryptoquick commented on bitcoin_blockchain/Cargo.toml
> +chrono = "0.4.24"
I think we change this to `chrono = { version = "0.4.24", default-features = false }`  as recommended here: https://github.com/chronotope/chrono/issues/602#issuecomment-1513829262

2023-04-27 20:19 UTC, dr-orlovsky commented on bitcoin_scripts/Cargo.toml
>  secp256k1 = { version = "0.24.2", features = ["global-context"] } # Remove after bitcoin #922
rust-bitcoin bug is still not fixed, but the pinning is not there anyway... And I am not sure why I decided that pinning was required the first place... So I think we can just remove the comment and that's it

2023-04-27 20:23 UTC, dr-orlovsky requested changes
My main comment was still not addressed: https://github.com/BP-WG/bitcoin_foundation/pull/18#pullrequestreview-1386422501

This PR also needs rebase

2023-04-29 17:29 UTC, crisdut commented
> My main comment was still not addressed: [#18 (review)](https://github.com/BP-WG/bitcoin_foundation/pull/18#pullrequestreview-1386422501)
> 
> This PR also needs rebase

I tried to merge and rebase to the master branch, but I encountered some challenges to make that. 

I saw the comments in PR #19, and I resolve to explain the goal to the branch:

Initially, I bumped amplify dependency in `descriptor-wallet` and `bp_foundation` two weeks ago (see [here](https://github.com/diba-io/bitmask-core/blob/4873ecce3dc5c429953579baebb3ebae781f763b/Cargo.toml#L108-L112)) to use `descriptor-wallet` in bitmask-core with WASM target.  Then, I opened this PR, and after approval, I would open the PR for `descriptor-wallet`.

2023-04-30 11:12 UTC, dr-orlovsky commented
@crisdut yes sure!

2023-10-25 22:54 UTC, closed without merging